WITH RECURSIVE ECOLI_DATA_GENERATION AS (
    SELECT A.*, 1 AS GENERATION
    FROM ECOLI_DATA A
    WHERE A.PARENT_ID IS NULL 
    
    UNION ALL
    
    SELECT E.*, GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA E INNER JOIN ECOLI_DATA_GENERATION G ON E.PARENT_ID = G.ID
)

SELECT COUNT(A.GENERATION) AS COUNT, A.GENERATION 
FROM ECOLI_DATA_GENERATION A
WHERE A.ID NOT IN (SELECT A.ID FROM ECOLI_DATA B WHERE B.PARENT_ID = A.ID)
GROUP BY A.GENERATION
ORDER BY A.GENERATION ASC