-- 코드를 입력하세요
SELECT DISTINCT A.APNT_NO, B.PT_NAME, B.PT_NO, A.MCDP_CD, C.DR_NAME, A.APNT_YMD 
FROM APPOINTMENT A INNER JOIN PATIENT B ON A.PT_NO = B.PT_NO
INNER JOIN DOCTOR C ON A.MDDR_ID = C.DR_ID
WHERE A.APNT_CNCL_YN = "N" AND A.MCDP_CD = "CS" AND A.APNT_YMD LIKE "2022-04-13%"
ORDER BY A.APNT_YMD